{"name": "test_2", "status": "failed", "statusDetails": {"message": "AssertionError: failing for demo purposes\nassert 0", "trace": "def test_2():\n        log = logging.getLogger('test_2')\n        time.sleep(1)\n        log.debug('after 1 sec')\n        time.sleep(1)\n        log.debug('after 2 sec')\n        time.sleep(1)\n        log.debug('after 3 sec')\n>       assert 0, 'failing for demo purposes'\nE       AssertionError: failing for demo purposes\nE       assert 0\n\ntest_demo.py:25: AssertionError"}, "start": 1663577344326, "stop": 1663577347354, "uuid": "91cc2dd8-3faa-4700-9adb-e510e24980ed", "historyId": "c0c0a28707fc9d4d177aa067505be564", "testCaseId": "ec16501b15041eec49611641414c42ee", "fullName": "test_case.demo_case.stu_demo.test_demo#test_2", "labels": [{"name": "parentSuite", "value": "test_case.demo_case.stu_demo"}, {"name": "suite", "value": "test_demo"}, {"name": "host", "value": "我不帅"}, {"name": "thread", "value": "10336-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.demo_case.stu_demo.test_demo"}]}