{"name": "test_assume[1-1]", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n2 Failed Assumptions:\n\ntest_demo.py:6: AssumptionFailure\n>>\tpytest.assume(3 == 4)\nAssertionError: assert False\n\ntest_demo.py:7: AssumptionFailure\n>>\tpytest.assume(5 == 9)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               2 Failed Assumptions:\nE               \nE               test_demo.py:6: AssumptionFailure\nE               >>\tpytest.assume(3 == 4)\nE               AssertionError: assert False\nE               \nE               test_demo.py:7: AssumptionFailure\nE               >>\tpytest.assume(5 == 9)\nE               AssertionError: assert False\n\nJ:\\programe\\python3\\lib\\site-packages\\six.py:718: FailedAssumption"}, "parameters": [{"name": "x", "value": "1"}, {"name": "y", "value": "1"}], "start": 1663569890933, "stop": 1663569891003, "uuid": "b3c3e3ff-7894-46fa-8668-b9f9e1ae4d34", "historyId": "0bed548013c0405ef69b982eeef94118", "testCaseId": "652245241652eb7ce1f973fa966ca17f", "fullName": "test_case.demo_case.stu_demo.test_demo#test_assume", "labels": [{"name": "parentSuite", "value": "test_case.demo_case.stu_demo"}, {"name": "suite", "value": "test_demo"}, {"name": "host", "value": "我不帅"}, {"name": "thread", "value": "8616-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.demo_case.stu_demo.test_demo"}]}