{"uid":"c3e03c6f5bfc94ed","name":"test_002_oa[case0]","fullName":"test_case.jnt_inter_case.jnt_app.test_debug.TestDebug#test_002_oa","historyId":"f39fbef4541977a6af7a6bc71b9f3732","time":{"start":1709696082365,"stop":1709696086735,"duration":4370},"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: '../../data/suidao1.jpeg'","statusTrace":"self = <pytest_demo.test_case.jnt_inter_case.jnt_app.test_debug.TestDebug object at 0x000001977C74D1C0>\ncase = {'Comment': '上传参数处理有误', 'ID': 'fukuan_10_c1', 'advice': '', 'case_description': '付款流程_上传附件', ...}\n\n    @allure.step('调试_OA')\n    @pytest.mark.debug\n    # @pytest.mark.parametrize()第一个参数为逗号分隔的字符串列表，第二个参数是值列表parametrize()\n    @pytest.mark.parametrize('case', excel.get_excel_data(\"debug\", \"OA\"))\n    def test_002_oa(self, case):\n        self.d_time.write_time_to_json()\n>       self.new.test_case_method(case)\n\ntest_case\\jnt_inter_case\\jnt_app\\test_debug.py:39: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ncommon\\data_deal.py:254: in test_case_method\n    response = self.reqe.req(request_method, api_url, params, headers, upload_files)\ncommon\\req_reload.py:44: in req\n    res = self.post_request(api_url, params, headers,upload_files)\ncommon\\req_reload.py:96: in post_request\n    response = requests.post(url=url, files=eval(upload_files), headers=header, verify=False)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n>   ???\nE   FileNotFoundError: [Errno 2] No such file or directory: '../../data/suidao1.jpeg'\n\n<string>:1: FileNotFoundError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[{"name":"init_connect","time":{"start":1709696082364,"stop":1709696082364,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentStep":false,"hasContent":false,"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0}],"testStage":{"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: '../../data/suidao1.jpeg'","statusTrace":"self = <pytest_demo.test_case.jnt_inter_case.jnt_app.test_debug.TestDebug object at 0x000001977C74D1C0>\ncase = {'Comment': '上传参数处理有误', 'ID': 'fukuan_10_c1', 'advice': '', 'case_description': '付款流程_上传附件', ...}\n\n    @allure.step('调试_OA')\n    @pytest.mark.debug\n    # @pytest.mark.parametrize()第一个参数为逗号分隔的字符串列表，第二个参数是值列表parametrize()\n    @pytest.mark.parametrize('case', excel.get_excel_data(\"debug\", \"OA\"))\n    def test_002_oa(self, case):\n        self.d_time.write_time_to_json()\n>       self.new.test_case_method(case)\n\ntest_case\\jnt_inter_case\\jnt_app\\test_debug.py:39: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ncommon\\data_deal.py:254: in test_case_method\n    response = self.reqe.req(request_method, api_url, params, headers, upload_files)\ncommon\\req_reload.py:44: in req\n    res = self.post_request(api_url, params, headers,upload_files)\ncommon\\req_reload.py:96: in post_request\n    response = requests.post(url=url, files=eval(upload_files), headers=header, verify=False)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n>   ???\nE   FileNotFoundError: [Errno 2] No such file or directory: '../../data/suidao1.jpeg'\n\n<string>:1: FileNotFoundError","steps":[{"name":"调试_OA","time":{"start":1709696082365,"stop":1709696086732,"duration":4367},"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: '../../data/suidao1.jpeg'\n","statusTrace":"  File \"D:\\Program Files\\Python\\Python39\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"D:\\Scripts\\python_code\\pytest_demo\\test_case\\jnt_inter_case\\jnt_app\\test_debug.py\", line 39, in test_002_oa\n    self.new.test_case_method(case)\n  File \"D:\\Scripts\\python_code\\pytest_demo\\common\\data_deal.py\", line 254, in test_case_method\n    response = self.reqe.req(request_method, api_url, params, headers, upload_files)\n  File \"D:\\Scripts\\python_code\\pytest_demo\\common\\req_reload.py\", line 44, in req\n    res = self.post_request(api_url, params, headers,upload_files)\n  File \"D:\\Scripts\\python_code\\pytest_demo\\common\\req_reload.py\", line 96, in post_request\n    response = requests.post(url=url, files=eval(upload_files), headers=header, verify=False)\n  File \"<string>\", line 1, in <module>\n","steps":[],"attachments":[],"parameters":[{"name":"case","value":"{'ID': 'fukuan_10_c1', 'case_description': '付款流程_上传附件', 'module': 'OA', 'envir': 'jnt_app_dev', 'pre_case': '', 'request_mode': 'post', 'case_url': '/oa/admin-api/system/file/procedure/upload', 'case_header': '{\"Authorization\":\"Bearer j::oa_token\"}', 'case_global_var': '', 'upload_files': \"{'file': open(r'../../data/suidao1.jpeg', 'rb')}\", 'case_preset': '', 'case_params': '', 'case_expect': '', 'Comment': '上传参数处理有误', 'advice': ''}"}],"attachmentStep":false,"hasContent":true,"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":0}],"attachments":[],"parameters":[],"attachmentStep":false,"hasContent":true,"stepsCount":1,"shouldDisplayMessage":true,"attachmentsCount":0},"afterStages":[{"name":"init_connect::0","time":{"start":1709696087535,"stop":1709696104019,"duration":16484},"status":"broken","statusMessage":"KeyboardInterrupt\n","statusTrace":"  File \"D:\\Program Files\\Python\\Python39\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\Program Files\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\Scripts\\python_code\\pytest_demo\\conftest.py\", line 11, in init_connect\n    print('会话之后关闭连接--pass')\n  File \"D:\\Scripts\\python_code\\pytest_demo\\conftest.py\", line 11, in init_connect\n    print('会话之后关闭连接--pass')\n  File \"_pydevd_bundle\\pydevd_cython_win32_39_64.pyx\", line 1187, in _pydevd_bundle.pydevd_cython_win32_39_64.SafeCallWrapper.__call__\n  File \"_pydevd_bundle\\pydevd_cython_win32_39_64.pyx\", line 627, in _pydevd_bundle.pydevd_cython_win32_39_64.PyDBFrame.trace_dispatch\n  File \"_pydevd_bundle\\pydevd_cython_win32_39_64.pyx\", line 1103, in _pydevd_bundle.pydevd_cython_win32_39_64.PyDBFrame.trace_dispatch\n  File \"_pydevd_bundle\\pydevd_cython_win32_39_64.pyx\", line 1065, in _pydevd_bundle.pydevd_cython_win32_39_64.PyDBFrame.trace_dispatch\n  File \"_pydevd_bundle\\pydevd_cython_win32_39_64.pyx\", line 585, in _pydevd_bundle.pydevd_cython_win32_39_64.PyDBFrame.do_wait_suspend\n  File \"D:\\Program Files\\JetBrains\\PyCharm_Community\\plugins\\python-ce\\helpers\\pydev\\pydevd.py\", line 1184, in do_wait_suspend\n    self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread)\n  File \"D:\\Program Files\\JetBrains\\PyCharm_Community\\plugins\\python-ce\\helpers\\pydev\\pydevd.py\", line 1199, in _do_wait_suspend\n    time.sleep(0.01)\n","steps":[],"attachments":[],"parameters":[],"attachmentStep":false,"hasContent":true,"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":0}],"labels":[{"name":"feature","value":"调试demo"},{"name":"tag","value":"debug"},{"name":"parentSuite","value":"test_case.jnt_inter_case.jnt_app"},{"name":"suite","value":"test_debug"},{"name":"subSuite","value":"TestDebug"},{"name":"host","value":"WIN-DVMNCVL70K8"},{"name":"thread","value":"19472-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_case.jnt_inter_case.jnt_app.test_debug"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"case","value":"{'ID': 'fukuan_10_c1', 'case_description': '付款流程_上传附件', 'module': 'OA', 'envir': 'jnt_app_dev', 'pre_case': '', 'request_mode': 'post', 'case_url': '/oa/admin-api/system/file/procedure/upload', 'case_header': '{\"Authorization\":\"Bearer j::oa_token\"}', 'case_global_var': '', 'upload_files': \"{'file': open(r'../../data/suidao1.jpeg', 'rb')}\", 'case_preset': '', 'case_params': '', 'case_expect': '', 'Comment': '上传参数处理有误', 'advice': ''}"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"cebb97cb4e74bfeb","status":"broken","statusDetails":"FileNotFoundError: [Errno 2] No such file or directory: '../../data/suidao1.jpeg'","time":{"start":1709695988788,"stop":1709695997215,"duration":8427}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["debug"]},"source":"c3e03c6f5bfc94ed.json","parameterValues":["{'ID': 'fukuan_10_c1', 'case_description': '付款流程_上传附件', 'module': 'OA', 'envir': 'jnt_app_dev', 'pre_case': '', 'request_mode': 'post', 'case_url': '/oa/admin-api/system/file/procedure/upload', 'case_header': '{\"Authorization\":\"Bearer j::oa_token\"}', 'case_global_var': '', 'upload_files': \"{'file': open(r'../../data/suidao1.jpeg', 'rb')}\", 'case_preset': '', 'case_params': '', 'case_expect': '', 'Comment': '上传参数处理有误', 'advice': ''}"]}